### ISSUE TITLE
Add 2 more buttons

### ISSUE THREAD

**Issue by ggdaltoso** [AEFeinstein/gbaZero#2]
Hi, @AEFeinstein ! What amazing project do you have here!

I would like to build something like yours but with 2 more buttons on the right side (A, B, X, Y).

I already have most of the pieces listed such as PowerBoost 1000C, the GBA Case (with those 2 more buttons) and for the others, like audio, display, etc, it would not be too difficult to get the pieces.

Since I do not have the knowledge to modify your project, I was thinking if you could not help me.

**Comment by AEFeinstein** [comment]
Hi @ggdaltoso. I'm not currently working on this project, nor do I plan to work on it.

If you want to modify it to add more buttons, you'll have to add them to the EAGLE schematic on some GPIO first (https://github.com/AEFeinstein/gbaZero/blob/master/CAD/gba-zero.sch), lay them out on the board (https://github.com/AEFeinstein/gbaZero/blob/master/CAD/gba-zero.brd), and modify the software to map those buttons (https://github.com/AEFeinstein/gbaZero#the-software).

That's all I can recommend. Good luck.

**Comment by ggdaltoso** [comment]
Thanks, @AEFeinstein 

I'll try to follow your guide. I forked your repo and, if you want, I could open a pull request with my modifications.

**Comment by AEFeinstein** [comment]
I don't have EAGLE installed anymore since it requires an Autocad account (I've since moved to KiCAD), so I wouldn't be able to verify your changes. I'd also like to keep this project with just two buttons, so it does not need to drill any more holes in the plastic. You can make whatever changes you want, but I won't accept a pull request.
